### ISSUE TITLE
How to host the documentation

### ISSUE THREAD

**Issue by silverhook** [Pelican-Elegant/documentation#1]
As indicated in https://github.com/Pelican-Elegant/pelican-elegant/issues/173#issuecomment-440179359 we would need to decide how to best host the new documentation and in what form.

My suggestion would be to eat our own dogfood and use Pelican with the Elegant theme for our documentation (as @talha131 did before). There are many other options as well though – wikis, pure markdown, https://readthedocs.io etc. etc.

Why i think that eating own dogfood would be best is that then we would have both static HTML documentation as well as a demo instance of the theme.

I would suggest that we organise the documentation as pages and add a blog part where we would publish release blog note posts.

Perhaps it would be best to set up a CI to build it and host it on GitHub Pages.

That way we would also have a testing instance (at least for released versions) that we can all refer to as the benchmark.

**Comment by silverhook** [comment]
Thanks, that’s a good list of items to address.

I’ll leave this up for a bit to let others comment if they have a different suggestion on how we should handle documentation.

**Comment by iranzo** [comment]
Using readthedocs is easy to setup and doesn't require to use external travis codes for pushing to branch, going for using pelican to render the page and even more, use elegant as theme could be great even if this means having to follow several steps:

[ ] Rename to XXX.github.io repo name
[ ] Move current content to `source` branch
[ ] leave master for 'rendered' output

**Comment by iranzo** [comment]
Some scripts on using token and travis build in github to publish to blog on updates
<https://gist.github.com/ShaunaGordon/0cbf0b8f2d667c5ec794>

**Comment by iranzo** [comment]
Also: <https://blog.minchin.ca/2017/05/deploying-pelican-with-travis-to-github.html>

**Comment by iranzo** [comment]
@silverhook can we get admin for this repo to set it up and then be downgraded again?

**Comment by silverhook** [comment]
ReadTheDocs is great, but I’m more in favour of continuing running the documentation on Pelican + Elegant.

My reasons:

- “self-hosted” static HTML
- can serve as a test-bed for Elegant (forks of the documentation repo)
- serves as a demo page – loads of themes don’t have one any more, as the original author moved to a different theme or even blogging service
- can double as a news outlet for releases and big announcements relating the theme (like Pelican’s own blog)

I’ll promote you both to Owner so you can set it up. Let me know when you’re ready and I’ll make you both Members again.

**Comment by iranzo** [comment]
I'll try to do it during today and list here the  commits (i'll go to the direct commit way until it's setup)

**Comment by talha131** [comment]
> Read the docs

Please no and never. We should eat our dog food and make sure we have a fully functional site to showcase the feature. A live website is no replacement of few demo pages.

ReadTheDocs makes sense for libraries. But for theme, it's not a good suit.

# Domain

Do we need to buy a domain for the site? If so I am willing to purchase a `.com` domain for 3 years and pass the ownership to the community? (Is it possible, a community owning a domain?)

**Comment by iranzo** [comment]
I'm preparing it to do it via github pages so that a domain is not needed and we can use something like pelican-elegant.github.io

A domain can be put pointing to it (I do have that done with https://citellus.org that is hosted on github pages)

**Comment by talha131** [comment]
We can also use netlify instead of github pages.

There is also gitlab which has better CI support. You don't have to rely on external tool like travis. We can use Gitlab only for compiling and hosting the documentation.

> A domain can be put pointing to it

Yes that's the plan. If we decide to get a domain.

**Comment by silverhook** [comment]
I’m also willing to pay for a .org/.com/.net domain, if needed. If we do that, it would make sense to transfer it to an organisation of trust though, so we don’t depend on a single person to run the domain.

For now, i think pelican-elegant.github.io is perfectly fine :)

---

(I wouldn’t mind moving Elegant to GitLab at all, but that seems like a separate question – @talha131 feel free to open a new issue for discussion, if you think we would benefit from the move.)

**Comment by talha131** [comment]
>  @talha131 feel free to open a new issue for discussion, if you think we would benefit from the move.)

At the moment I am not sure Gitlab is a better choice. I put forward the alternates so that the community can reach a better decision.

Hosting documentation at gitlab will NOT result in migrating elegant from here. 

Whoever takes up this task will be a better judge.

**Comment by silverhook** [comment]
@iranzo, you mean [a personal access token](https://github.com/settings/tokens/)? Does it need any specific scopes?

GPG over e-mail sounds good. Your valid pubkey’s fingerprint is: `8C6C 121B 4EE1 CA05 09CC 3F98 0348 2366 5BD8 E1E4` right?

---

(re requirements for Owner vs Member vs general public, we should have that discussion soon-ish, but in a separate thread …AFAIK @talha131 was already working on some early proposal)

**Comment by iranzo** [comment]
Yes, if not for you, we will need another 'account' for the bot that has 'write' access at least to the repo.

yes, my key is:

```pub   2048D/5BD8E1E4 2012-05-24
uid                  Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>
uid                  [jpeg image of size 4452]
uid                  Pablo Iranzo Gómez <Pablo.Iranzo@uv.es>
uid                  Pablo Iranzo Gómez <Pablo.Iranzo@alufis35.uv.es>
uid                  Pablo Iranzo Gómez <Pablo.Iranzo@redhat.com>
sub   2048g/E09DFF31 2012-05-24
```

**Comment by silverhook** [comment]
I’m OK with lending mine (at least until we find a better solution).

Do I need to enable any scopes?

**Comment by iranzo** [comment]
From <https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/> 

And as we do need read/write it should be 'repo', probably status, deployment, public_repo

If something is missing we can change with one with more privileges

**Comment by silverhook** [comment]
Thanks. Generated and sent to you by encrpyted e-mail.

**Comment by iranzo** [comment]
Thanks will continue later today and add it

**Comment by iranzo** [comment]
Please do check <https://pelican-elegant.github.io/>

And downgrade back my user.

If everything OK, I'll document how it was done in the following days

**Comment by iranzo** [comment]
Build example at <https://travis-ci.org/Pelican-Elegant/documentation/builds/464690087>

**Comment by silverhook** [comment]
Awesome, thanks.

I changed @iranzo and @ashwinvis ’s invitation back to Member (discussion on roles here: https://github.com/Pelican-Elegant/elegant/issues/193)

@ashwinvis, @iranzo: would you two volunteer to be responsible for maintaining the CI?

**Comment by iranzo** [comment]
I don't mind doing it, as I also use it for other projects, whatever helps for one, helps the others

**Comment by ashwinvis** [comment]
Sure count me in. I would be interested as I still use the theme.

-------- Original Message --------

**Comment by silverhook** [comment]
Cool :+1:

**Comment by iranzo** [comment]
Should this be closed now?

**Comment by silverhook** [comment]
Yeah, I think we’re good.

@ashwinvis, if you see any reason to re-open this, feel free to do it (or let me know, if you can’t).

**Comment by iranzo** [comment]
URL on what was done <https://iranzo.github.io/blog/2018/12/07/elegant-website-ci/>

If you're ok, I can copy to documentation and pr it

**Comment by silverhook** [comment]
Great stuff! I think it’d be a good idea to merge it into the new documentation site :+1:
