### ISSUE TITLE
Is a separate repository necessary for rendered pages

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/documentation#12]
@iranzo Is it necessary to put rendered pages on a different repo https://github.com/Pelican-Elegant/pelican-elegant.github.io? Can we put them in a, say `published` branch of this repo and then host on github pages?

**Comment by iranzo** [comment]
No, it's not required to put it on a different, for personals I think it was required to do it so.

For organizations, it can be 'any branch', thing is that we want it to be automated and having it separated give us the chance to avoid messing with the repo we use to host the actual documentation with different branches.

**Comment by talha131** [comment]
Thanks for the explanation. As you are leading the effort to host the documentation, I trust your best judgement.
