### ISSUE TITLE
Accordion is not working

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/documentation#13]
Accordion is not working 

https://pelican-elegant.github.io/categories.html

Related to 

https://github.com/Pelican-Elegant/elegant/issues/189
https://github.com/Pelican-Elegant/elegant/pull/131

**Comment by silverhook** [comment]
Hehe, and dog-fooding is already paying off ;)

**Comment by AWegnerGitHub** [comment]
This can be closed. We fixed it :)
