### ISSUE TITLE
Remove attribution to @talha131 blog in the footer

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/documentation#18]
It's community driven now therefore, reference to personal blog must be removed.

![](https://i.imgur.com/PPtItZi.png)

**Comment by silverhook** [comment]
I suggest to change it to something like:

“Elegant contributors”

other options that pop to mind:

- Contributors to the Elegant project
- Elegant authors
- Elegant community
- …

**Comment by talha131** [comment]
How about

"Elegant documentation is an Open Source Project, which is licensed under a ...."?

**Comment by silverhook** [comment]
> "Elegant documentation is an Open Source Project, which is licensed under a ...."?

I think we should keep to the original template, so what I imagine is something like:

> Elegant documentation by [Elegant contributors](https://pelican-elegant.github.io/) is licensed under a [CC-BY-SA-4.0 license](https://creativecommons.org/licenses/by-sa/4.0/).

and at the other end simply keep:

> Powered by [Pelican](https://getpelican.com/). Theme: [Elegant](https://pelican-elegant.github.io/)

That would be the license of the page/documentation content.

What Elegant (as a theme) is, we should explain in the “About Me” part.

**Comment by talha131** [comment]
> Elegant documentation by Elegant documentation contributors is licensed under a CC-BY-SA-4.0 license.

There is to much "elegant" in it 😆

My suggestion

"Elegant theme documentation is licensed under a CC-BY-SA-4.0 license."

**Comment by silverhook** [comment]
Is this to be closed now?

**Comment by talha131** [comment]
No I need to update the configuration. Related to #41 

I will do it in a while.

**Comment by silverhook** [comment]
In connection with #41 we also need to update the `pelicanconf.py` file:

from:

```py
SITE_LICENSE = u'Elegant theme documentation is licensed under a CC-BY-SA-4.0 license.'
```

to at least

```py
SITE_LICENSE = u'Elegant theme documentation is licensed under a CC-BY-4.0 license.'
````

… or better yet to:


```py
SITE_LICENSE = u'Elegant theme documentation is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY-4.0 license</a>.'
````

… so the visitor can see the license text by just clicking on the link.

**Comment by talha131** [comment]
That's the plan.
