### ISSUE TITLE
Do we want to setup analytics?

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/documentation#26]
I was thinking that as we do have the site claimed on google (to submit sitemap, etc) it would be also 'easy' to push a tracker so that we can get website statistics.

So... room open for discussion here...

**Comment by talha131** [comment]
I vote against it for following reasons,

1. In my experience most Pelican users are tech savvy (like you and @silverhook use PGP) and privacy conscious. That's one of the reason behind creating [share-post](https://github.com/getpelican/pelican-plugins/tree/master/share_post) plugin, if you look up the discussion around it on IRC
1. Lets say we collect the analytics. What are we going to use it for? Is there any question or parameter for which we want to collect data?
1. Who is going to review the analytics results and make necessary changes? Our plate is already full. 3.0 is big milestone.

The only way to go ahead with collecting analytics is, if we make the data public and use a service that does not have the history of tracking users across the sites. This means Google Analytics is out.

If collected data is public then most user will not have objection on collecting it. It may motivate the contributors too, when they will see x number of users are visiting the docs.

Alternates are, (off the top of my head)

1. https://statcounter.com/ (It's not free and I am not sure if the data can be made public easily)
1. Alternate is PiWik which is OSS but needs to be hosted

So my final remarks is to close this ticket. We may visit it sometime in future. Perhaps after 3.0.

Lets see what others have to say on the topic.

**Comment by talha131** [comment]
> I don't see why share-post has to do with statistics

Share-post enables sharing post on social sites without the user tracking that comes with usual social widgets.

I understand your post. Lets see what others have to say on this topic.

**Comment by silverhook** [comment]
I pretty much agree with @talha131 on this topic and in my personal opinion, I’d also be for simply closing this issue.

Right now I see no benefit in using analytics – especially something as simple as site analytics.

If we were eventually to monitor our project to better fit it our community, I would instead suggest a more thorough approach, I’d go for something like Kibana/[GrimoireLab](https://chaoss.github.io/grimoirelab/) – either self-hosted or through https://cauldron.io/

But right now, I think we have more than enough work on our hands to get 2.0 and 3.0 ready and any analytics would just be taking attention away from where it’s needed.

The other point, of course, is what our users would think in terms of privacy, if we ran analytics. Even if we find a good reason to use analytics, we should still ask ourselves if our benefits outweigh the negative impact on the privacy of our users.

We could also leave this issue open and tag it to review for (post-)3.0 and collect our community’s thoughts in here until then.

**Comment by iranzo** [comment]
+1 
Let's close it
