### ISSUE TITLE
Links in top menu bar are not working

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/documentation#29]
Categories, archives, and tags menu items, they all point to the home page.

I suspect its due to this commit https://github.com/Pelican-Elegant/elegant/pull/186/

**Comment by AWegnerGitHub** [comment]
It looks like this might be another Pelican 4.0 thing. 

From the [settings documentation](http://docs.getpelican.com/en/stable/settings.html) (search "Direct Templates")

> `DIRECT_TEMPLATES` work a bit differently than noted above. Only the `_SAVE_AS` settings are available, but it is available for any direct template.

Example: `ARCHIVES_SAVE_AS = 'archives.html'`

---

This is a bit confusing though as another section on the same page says this:

> URLs for direct template pages are theme-dependent. Some themes use corresponding `*_URL` setting as string, while others hard-code them: `'archives.html'`, `'authors.html'`, `'categories.html'`, `'tags.html'`.

I've asked for clarification in https://github.com/getpelican/pelican/issues/2490

**Comment by talha131** [comment]
Thank @AWegnerGitHub. I have assigned the issue to you. 

Please also see this issue

https://github.com/Pelican-Elegant/elegant/issues/203

**Comment by iranzo** [comment]
So probably yes, 4.x issue let's see what we do get on the issue you raised!

**Comment by AWegnerGitHub** [comment]
> pelican itself doesn't use or generate `*_URL` variables for direct templates.

https://github.com/getpelican/pelican/issues/2490#issuecomment-446666400

So, either we define the `*_URL` values in the config file, or we need to utilize another option? The comment linked above gives an example. Would this be a good idea for us?

**Comment by iranzo** [comment]
+1 on defining them in our 'elegant setup guide'

**Comment by talha131** [comment]
We should strive for making Elegant work for the user out of the box. We already have too many options to configure. We should,

1. Provide reasonable defaults such that site can be up and running without any configuration
1. May provide variables to fine tune the site

The example [here](https://github.com/getpelican/pelican/issues/2490#issuecomment-446666400) is pretty good.

```html
<a href='{{ SITEURL }}/{{ ARCHIVES_URL or 'archives' }}'>Link to archives</a>
```

I think it covers both the points. 

@AWegnerGitHub, if @iranzo does not disagree or bring up a counter point, please open up a PR in elegant repo with the fixes.

----

I did a quick test locally and it worked

```html
<li {% if page_name == 'categories' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ CATEGORIES_URL or 'categories' }}">Categories</a></li>
<li {% if page_name == 'tags' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ TAGS_URL or 'tags' }}">Tags</a></li>
<li {% if page_name == 'archives' %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ ARCHIVES_URL or 'archives'}}">Archives</a></li>
```

**Comment by iranzo** [comment]
Validated in live website after elegant merge that triggered documentation rebuild

**Comment by talha131** [comment]
Thank you @iranzo for testing it for me.
