### ISSUE TITLE
Add annoncement article for 2.0 release

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/documentation#52]
1. Add change log
1. Add note that the project is now community driven. Mention @silverhook 
1. Make special mention of @iranzo and @AWegnerGitHub 
1. Add thanks https://github.com/Pelican-Elegant/elegant/issues/227

**Comment by silverhook** [comment]
I’ll give it a quick go and submit a PR, so we can refine it together, if needed.

**Comment by talha131** [comment]
@silverhook I think

> Add note that the project is now community driven. Mention @silverhook

can be placed in a separate article and that article can be placed in "Announcement" category.

**Comment by silverhook** [comment]
I’ll try to squeeze it in, but if it feels off, we can take it out and into a separate post.

Any concerns against this being in the same PR?

**Comment by silverhook** [comment]
A good question is what we should do with https://github.com/Pelican-Elegant/elegant/blob/master/RELEASE_NOTES.md then.

One option would be to rename it into a traditional `ChangeLog` – [see Wikipedia article][wp] – and make it a rule that when a new feature or (big) bug is fixed, it should be documented there as well in the same PR.

Then we could simply include the changelog into the release notes, when we write them.

[wp]: https://en.wikipedia.org/wiki/Changelog

**Comment by talha131** [comment]
Right.

1. Release Notes → Change log
1. Ask contributors to update it. (It should be updated with every PR, in my opinion)
1. Use change log to write Release Notes article with every release.

> I’ll try to squeeze it in, but if it feels off, we can take it out and into a separate post.
> Any concerns against this being in the same PR?

No issues. Though, I think release notes should not have project management announcement in it, unless necessary. It makes sense to put it inside Release Notes in cases where developer have no other mean of communication. In our case, we have a whole site dedicated for documentation. It would be better if we keep things granular.

Anyway, thanks for taking up this issue.

**Comment by silverhook** [comment]
Agreed.

I will try to write it into two separate posts then.

**Comment by silverhook** [comment]
@talha131, can you open up an issue or even pull request to update the `CONTRIBUTING.md` to include the ChangeLog rule? I don’t think we need to discuss or vote on it – it feel more like just something we forgot to explicitly mention, as you were doing this before already, and it is a commonly-accepted best practice.

**Comment by talha131** [comment]
Will do.

**Comment by talha131** [comment]
> can you open up an issue or even pull request to update the `CONTRIBUTING.md`

done

**Comment by silverhook** [comment]
Damn, I should have committed upstream and created a PR for the draft I wrote. I’ll send mine as well more for comparison with @iranzo’s, if there’s anything useful in mine and then concentrate on working on the community announcement.
