### ISSUE TITLE
How to get random  Disqus Identifier ?

### ISSUE THREAD

**Issue by azzamsa** [Pelican-Elegant/documentation#58]
It's mentioned "Set it to any unique string you want" [here](https://github.com/Pelican-Elegant/documentation/blob/master/content/Elegant%20-%20Pelican%20Theme/disqus-comments.md). But how do you guys get that random number before the "slug" thing ?

```
Disqus_identifier: 7mh4xjn-search-engine-and-social-media-optimization
```

Thanks :)

**Comment by iranzo** [comment]
Theoretically, disqus is based on both site + slug if you don't specify it, and as 'slug' has to be independent anyway it shouldn't be an issue unless you manually repeat the same identifier on different articles

**Comment by azzamsa** [comment]
Thanks a lot Iranzo.

**Comment by talha131** [comment]
@azzamsa 

>  unless you manually repeat the same identifier on different articles

This is the key. You just have to make sure your identifiers are always unique and immutable.

The unique number you see was just my attempt to ensure "uniqueness". I picked it from my git commit hashes. 😄 I don't know what source other contributors used.

**Comment by azzamsa** [comment]
>  I picked it from my git commit hashes.

Wow, nice idea :tada:
