### ISSUE TITLE
Submit sitemap to google sites

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/documentation#7]

**Comment by iranzo** [comment]
Assign to me

**Comment by iranzo** [comment]
Depends on #8

**Comment by iranzo** [comment]
Done:

![image](https://user-images.githubusercontent.com/312463/49650529-bc551e00-fa2c-11e8-84b0-bb0834827973.png)

**Comment by talha131** [comment]
Thank you @iranzo. Really appreciated!

**Comment by iranzo** [comment]
My pleasure!
